// dry.js — a fake OpenCodeClient for testing the pipeline without a live
// provider. Activated with BIGPICKLE_DRY=1 (optionally BIGPICKLE_DRY_FAIL=stage
// to force that stage to score below threshold, exercising needs-review).
//
// The dry client writes realistic stage outputs into the job folder so the
// auto-checks and evaluation flow actually run end-to-end.

import fs from 'node:fs'
import path from 'node:path'

/** Resolve the current stage from the session title "[<id> <StageLabel>] name". */
function stageFromTitle (title) {
  const m = String(title || '').match(/\[[^\]]*\s(Plan|Build|Review|Test|Deploy)\]/i)
  if (m) return m[1].toLowerCase()
  return ''
}

export class DryClient {
  constructor (opts = {}) {
    this.failStage = opts.failStage || process.env.BIGPICKLE_DRY_FAIL || ''
    this.dir = ''
  }

  async health () {
    return { version: 'dry-run-not-real', urls: ['http://127.0.0.1:9'] }
  }

  async createSession ({ title = '', directory = '', agent = 'builder', model }) {
    this.dir = directory
    this.stage = stageFromTitle(title)
    this.last = { title, agent, model }
    return { id: 'dry-' + Math.random().toString(36).slice(2, 8) }
  }

  async promptAndWait (sessionID, text) {
    const stage = this.stage || 'build'
    const dir = this.dir
    const b = '// generated by the dry-run pipeline client\n'
    fs.mkdirSync(path.join(dir, '.bp'), { recursive: true })

    if (stage === 'plan') {
      fs.writeFileSync(path.join(dir, 'DESIGN.md'), [
        '# Dry design',
        '',
        '## Architecture',
        '- Single self-contained node app, no external deps.',
        '- REST-ish CLI: read input → compute → print.',
        '## Data',
        '- Files on disk, JSON.',
        '## API',
        '- none (CLI)',
        '## Dependencies',
        '- node 18+',
        ''
      ].join('\n'))
      fs.writeFileSync(path.join(dir, '.bp', 'stages.json'), JSON.stringify({
        build: 'Build the dry app: a CLI that sums numbers. Write README.md and BUILD_REPORT.md.',
        review: 'Review the dry app. Write REVIEW.md, end with SCORE: <0-100> and CRITIQUE: <short>.',
        test: 'Test the dry app: add tests for summing. Write TEST_REPORT.md.',
        deploy: 'Finish the dry app: write DEPLOY.md and put a zip in dist/.'
      }, null, 2))
      return 'DESIGN.md and stage prompts written.'
    }

    if (stage === 'build') {
      fs.writeFileSync(path.join(dir, 'sum.js'), b + 'const sum = (a, b) => Number(a) + Number(b);\nmodule.exports = { sum };\n')
      fs.writeFileSync(path.join(dir, 'cli.js'), b + 'const { sum } = require("./sum.js");\nconst [a, x] = process.argv.slice(2);\nconsole.log(sum(a, x));\n')
      fs.writeFileSync(path.join(dir, 'README.md'), '# Dry App\n\nSums two numbers. `node cli.js 1 2` → 3\n')
      fs.writeFileSync(path.join(dir, 'BUILD_REPORT.md'), '# Build report — dry app\n\nBuilt a CLI that sums numbers. See README.md.\n')
      return 'Dry app implemented.'
    }

    if (stage === 'review') {
      fs.writeFileSync(path.join(dir, 'REVIEW.md'), [
        '# Review — dry app',
        '',
        '## Findings',
        '- Correct and minimal implementation of the sum CLI.',
        '- Missing edge-case tests (empty input, non-numbers).',
        '- No external dependencies — good.',
        '',
        '## Verdict',
        'Solid overall; add a couple of edge-case tests before shipping.'
      ].join('\n'))
      return 'SCORE: 88\nCRITIQUE: solid minimal implementation, add edge case tests'
    }

    if (stage === 'test') {
      fs.mkdirSync(path.join(dir, 'test'), { recursive: true })
      fs.writeFileSync(path.join(dir, 'test', 'sum.test.js'), b + 'const assert = require("assert");\nconst { sum } = require("../sum.js");\nassert.strictEqual(sum(1, 2), 3);\nassert.strictEqual(sum(-1, 1), 0);\nconsole.log("tests pass");\n')
      fs.writeFileSync(path.join(dir, 'TEST_REPORT.md'), '# Test report — dry app\n\nsum.test.js passes: 2 cases.\n')
      return 'Tests written and passing.'
    }

    if (stage === 'deploy') {
      fs.mkdirSync(path.join(dir, 'dist'), { recursive: true })
      fs.writeFileSync(path.join(dir, 'dist', 'dry-app.zip'), 'PK-dry')
      fs.writeFileSync(path.join(dir, 'DEPLOY.md'), '# Deploy — dry app\n\n`node cli.js 1 2`. Package: dist/dry-app.zip\n')
      return 'Release finalized.'
    }

    return 'ok'
  }

  async activeSessions () { return {} }
  async sendPrompt () { return {} }
  async interrupt () { return {} }
  async messages () { return { messages: [] } }
  async setModel () { return {} }
  async setAgent () { return {} }
  async getSession () { return { id: 'dry' } }
  async listSessions () { return [] }
}

/** The evaluateStage scorer call goes through ctx.runScorer — this is the
 *  dry implementation used by the orchestrator. */
export async function dryRunScorer (scorer, job) {
  const stage = job.stage
  if (process.env.BIGPICKLE_DRY_FAIL && process.env.BIGPICKLE_DRY_FAIL === stage) {
    return JSON.stringify({ score: 30, critique: `dry-forced failure for ${stage}` })
  }
  return JSON.stringify({ score: 90, critique: 'dry scorer: good' })
}

export default DryClient